services:
  backend:
    image: ${APP_IMAGE:-ghcr.io/fega-kt/backend-mikroorm:latest}
    container_name: zhizhu-backend
    restart: unless-stopped
    environment:
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_SECRET_PATH: ${VAULT_SECRET_PATH}
      VAULT_AUTH_METHOD: ${VAULT_AUTH_METHOD}
    ports:
      - "127.0.0.1:${APP_PORT:-3000}:3000"
    networks:
      - zhizhu_net

networks:
  zhizhu_net:
    external: true
